# pytest.ini
[pytest]
pythonpath = .
env =
    DATABASE_URL=sqlite:///:memory:
    SECRET_KEY=test
    ALGORITHM=HS256
    ACCESS_TOKEN_EXPIRE_MINUTES=30
    AWS_ACCESS_KEY_ID=test_key
    AWS_SECRET_ACCESS_KEY=test_secret
    BUCKET_NAME=test-bucket
    REGION_NAME=us-east-1
filterwarnings =
    ignore::DeprecationWarning:pydantic
addopts = --cov=. --cov-report=term-missing
